# Generated by Django 3.0.6 on 2020-06-02 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensPontoControle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=300)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pontocontrole',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reluci.GrupoPontoControle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupopontocontrole',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reluci.ItensPontoControle'),
        ),
    ]
