# Generated by Django 3.0.6 on 2020-06-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0002_auto_20200602_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontocontrole',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('ATENDE', 'Atende'), ('ATENDE_PARCIALMENTE', 'Atende parcialmente'), ('NAO_ATENDE', 'Não atende')], max_length=30, null=True),
        ),
    ]
