# Generated by Django 3.0.6 on 2020-06-02 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0003_auto_20200602_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='nome',
        ),
        migrations.AddField(
            model_name='atividade',
            name='status',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não iniciado'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado')], default='NAO_INICIADO', max_length=30),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grupopontocontrole',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='reluci.ItensPontoControle'),
        ),
    ]
