# Generated by Django 3.0.6 on 2020-06-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0004_auto_20200602_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontocontrole',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='reluci.GrupoPontoControle'),
        ),
    ]
