# Generated by Django 3.0.6 on 2020-06-03 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0005_auto_20200603_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupopontocontrole',
            name='ponto_controle_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reluci.GrupoPontoControle'),
        ),
    ]
