# Generated by Django 3.0.6 on 2020-06-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0007_auto_20200603_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItensPontoControle',
            new_name='ItemAbordagem',
        ),
    ]
