# Generated by Django 3.0.6 on 2020-06-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0008_auto_20200604_1633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrupoPontoControle',
            new_name='ItemGestao',
        ),
    ]
