# Generated by Django 3.0.6 on 2020-06-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0009_auto_20200604_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensGestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=300)),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True)),
                ('classificacao', models.CharField(blank=True, choices=[('ATENDE', 'Atende'), ('ATENDE_PARCIALMENTE', 'Atende parcialmente'), ('NAO_ATENDE', 'Não atende')], max_length=30, null=True)),
                ('status', models.CharField(choices=[('NAO_INICIADO', 'Não iniciado'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado')], default='NAO_INICIADO', max_length=30)),
                ('ponto_controle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reluci.ItensGestao')),
            ],
        ),
    ]
