# Generated by Django 3.0.6 on 2020-06-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0010_itensgestao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItensGestao',
        ),
    ]
