# Generated by Django 3.0.6 on 2020-06-08 14:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0013_pontocontrole_sintese'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='observacao',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
