# Generated by Django 3.0.6 on 2020-06-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0016_auto_20200608_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tarefa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='reluci.Tarefa'),
        ),
    ]
