# Generated by Django 3.0.6 on 2020-06-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0017_auto_20200608_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpontocontrole',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('ATENDE', 'Atende'), ('ATENDE_PARCIALMENTE', 'Atende parcialmente'), ('NAO_ATENDE', 'Não atende')], max_length=30, null=True),
        ),
    ]
