# Generated by Django 3.0.6 on 2020-06-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0018_subpontocontrole_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpontocontrole',
            name='ponto_controle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reluci.PontoControle'),
        ),
    ]
