# Generated by Django 3.0.6 on 2020-06-08 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0019_auto_20200608_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='status',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não iniciado'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO', 'Aguardando'), ('FINALIZADO', 'Finalizado')], default='NAO_INICIADO', max_length=30),
        ),
        migrations.AlterField(
            model_name='itemgestao',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_gestao', to='reluci.ItemAbordagem'),
        ),
        migrations.AlterField(
            model_name='pontocontrole',
            name='status',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não iniciado'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO', 'Aguardando'), ('FINALIZADO', 'Finalizado')], default='NAO_INICIADO', max_length=30),
        ),
        migrations.AlterField(
            model_name='subpontocontrole',
            name='ponto_controle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_pontos_controle', to='reluci.PontoControle'),
        ),
        migrations.AlterField(
            model_name='subpontocontrole',
            name='status',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não iniciado'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO', 'Aguardando'), ('FINALIZADO', 'Finalizado')], default='NAO_INICIADO', max_length=30),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não iniciado'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO', 'Aguardando'), ('FINALIZADO', 'Finalizado')], default='NAO_INICIADO', max_length=30),
        ),
    ]
