# Generated by Django 3.0.6 on 2020-06-08 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0021_auto_20200608_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='ponto_controle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='reluci.PontoControle'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='sub_ponto_controle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='reluci.SubPontoControle'),
        ),
    ]
