# Generated by Django 3.0.6 on 2020-06-10 14:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0022_auto_20200608_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'ordering': ('codigo',)},
        ),
        migrations.AlterModelOptions(
            name='itemabordagem',
            options={'ordering': ('codigo',)},
        ),
        migrations.AlterModelOptions(
            name='itemgestao',
            options={'ordering': ('codigo',)},
        ),
        migrations.AlterModelOptions(
            name='pontocontrole',
            options={'ordering': ('codigo',)},
        ),
        migrations.AlterModelOptions(
            name='subpontocontrole',
            options={'ordering': ('codigo',)},
        ),
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ('codigo',)},
        ),
        migrations.AddField(
            model_name='atividade',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pontocontrole',
            name='analise',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subpontocontrole',
            name='observacao',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='observacao',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
