# Generated by Django 3.0.6 on 2020-06-10 14:59

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reluci', '0023_auto_20200610_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontocontrole',
            name='analise',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='observacao',
        ),
        migrations.CreateModel(
            name='ObservacaoTarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', ckeditor.fields.RichTextField()),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reluci.Tarefa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObservacaoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', ckeditor.fields.RichTextField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reluci.Atividade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnaliseSubPontoControle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analise', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sub_ponto_controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reluci.SubPontoControle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalisePontoControle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analise', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ponto_controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reluci.PontoControle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
