# Generated by Django 3.0.6 on 2020-06-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0024_auto_20200610_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpontocontrole',
            name='observacao',
        ),
    ]
