# Generated by Django 3.0.6 on 2020-06-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0026_auto_20200610_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analisepontocontrole',
            old_name='updated_at',
            new_name='alterado',
        ),
        migrations.RenameField(
            model_name='analisepontocontrole',
            old_name='created_at',
            new_name='criado',
        ),
    ]
