# Generated by Django 3.0.6 on 2020-06-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0028_auto_20200610_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisepontocontrole',
            name='ponto_controle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='reluci.PontoControle'),
        ),
    ]
