# Generated by Django 3.0.6 on 2020-06-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0030_remove_atividade_observacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpontocontrole',
            name='classificacao',
        ),
        migrations.RemoveField(
            model_name='subpontocontrole',
            name='status',
        ),
        migrations.AddField(
            model_name='analisesubpontocontrole',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('ATENDE', 'Atende'), ('ATENDE_PARCIALMENTE', 'Atende parcialmente'), ('NAO_ATENDE', 'Não atende')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='analisesubpontocontrole',
            name='status',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não iniciado'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO', 'Aguardando'), ('FINALIZADO', 'Finalizado')], default='NAO_INICIADO', max_length=30),
        ),
    ]
