# Generated by Django 3.0.6 on 2020-06-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0031_auto_20200616_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgestao',
            name='percentual',
            field=models.IntegerField(default=0),
        ),
    ]
