# Generated by Django 3.0.7 on 2020-06-22 16:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0033_auto_20200619_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacaoatividade',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observacaotarefa',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analisepontocontrole',
            name='analise',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Análise'),
        ),
        migrations.AlterField(
            model_name='analisepontocontrole',
            name='classificacao',
            field=models.CharField(choices=[('NAO_AVALIADO', 'Não avaliado'), ('ATENDE', 'Atende'), ('ATENDE_PARCIALMENTE', 'Atende parcialmente'), ('NAO_ATENDE', 'Não atende')], default='NAO_AVALIADO', max_length=30, verbose_name='Classificação'),
        ),
    ]
