# Generated by Django 3.0.7 on 2020-06-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0034_auto_20200622_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observacaoatividade',
            name='concluida',
        ),
        migrations.RemoveField(
            model_name='observacaotarefa',
            name='concluida',
        ),
        migrations.AddField(
            model_name='observacaoatividade',
            name='status',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não iniciado'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO', 'Aguardando'), ('FINALIZADO', 'Finalizado')], default='NAO_INICIADO', max_length=30),
        ),
        migrations.AddField(
            model_name='observacaotarefa',
            name='status',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não iniciado'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO', 'Aguardando'), ('FINALIZADO', 'Finalizado')], default='NAO_INICIADO', max_length=30),
        ),
    ]
