# Generated by Django 3.0.7 on 2020-06-22 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0035_auto_20200622_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='status',
        ),
        migrations.AlterField(
            model_name='observacaotarefa',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to='reluci.Tarefa'),
        ),
    ]
