# Generated by Django 3.0.7 on 2020-06-24 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reluci', '0041_auto_20200624_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacaotarefaatividade',
            name='atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observacoes_atividade', to='reluci.Atividade'),
        ),
    ]
