# Generated by Django 3.0.6 on 2020-05-29 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sigefes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaContribuicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, null=True)),
                ('descricao', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DespesaPrevidenciariaPatronal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segregacao_funcao.ContaContribuicao')),
                ('unidade_gestora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigefes.UnidadeGestora')),
            ],
        ),
    ]
