# Generated by Django 3.0.6 on 2020-05-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeGestora',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
