# Generated by Django 3.0.6 on 2020-06-02 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organograma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='entidade_auditora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organograma.Entidade'),
        ),
    ]
