# Generated by Django 3.0.7 on 2020-07-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organograma', '0002_auto_20200602_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='sigla',
            field=models.CharField(default='SIGLA', max_length=30),
            preserve_default=False,
        ),
    ]
